name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "esarandon@gmail.com"
          git config --global user.name "esarandon"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the React app
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
